config/routes.rb
Sosnuli::Application.routes.draw do

  get "omniauth_callbacks/facebook"
  get "omniauth_callbacks/vkontakte"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to:'home#index'

  resources :discussions do
    resources :posts
  end
  
  resources :videos, only: [:show]

  get :admin, to: 'admin#index'
  namespace :admin do
    resources :videos
    resources :discussions
  end
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  belongs_to :room

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :discussion
  belongs_to :user
  
  validates :content, presence: true#, length: { in: 7..1232 }
end

app/models/role.rb
class Role < ActiveRecord::Base
  include TheRole::Role
end

app/models/room.rb
class Room < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  has_many :discussions, dependent: :destroy
  has_many :videos, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  include TheRole::User

  has_many :videos
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :omniauthable

  before_create :default_name


  def self.find_for_vkontakte_oauth access_token
    if user = User.where(url: access_token.info.urls.Vkontakte).first
      user
    else 
      User.create!(provider: access_token.provider, url: access_token.info.urls.Vkontakte, 
                   name: access_token.info.name,
                   email: access_token.extra.raw_info.domain+'<hh user=vk>.com', 
                   password: Devise.friendly_token[0,20]) 
    end
  end


  private 
  def default_name
    self.name = "Guest #{rand(9999)}"
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  belongs_to :room

  validates :content,   presence: true
  validates :title,     presence: true
  validates :room_id,   presence: true
end

app/controllers/admin/discussions_controller.rb
class Admin::DiscussionsController < ApplicationController
  layout 'admin_application'
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]

  def index
    @discussions = Discussion.all
  end

  def show
  end

  def new
    @discussion = Discussion.new
  end

  def edit
  end

  def create
    @discussion = Discussion.new(discussion_params)

    if @discussion.save
      redirect_to polymorphic_path([:admin, @discussion]), notice: 'Discussion was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @discussion.update(discussion_params)
      redirect_to polymorphic_path([:admin, @discussion]), notice: 'Discussion was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @discussion.destroy
    redirect_to polymorphic_path([:admin, :discussions]), notice: 'Discussion was successfully destroyed.'
  end

  private
    def set_discussion
      @discussion = Discussion.find params[:id]
    end

    def discussion_params
      params[:discussion]
      params.require(:discussion).permit(:description, :title, :room_id, :short)
    end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  layout 'admin_application'
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  def index
    @videos = Video.all
  end

  def show
  end

  def new
    @video = Video.new
  end

  def edit
  end

  def create
    @video = Video.new(video_params)

    if @video.save
      redirect_to polymorphic_path([:admin, @video]), notice: 'Video was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @video.update(video_params)
      redirect_to polymorphic_path([:admin, @video]), notice: 'Video was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @video.destroy
    redirect_to polymorphic_path([:admin, :videos]), notice: 'Video was successfully destroyed.'
  end

  private
    def set_video
      @video = Video.find params[:id]
    end

    def video_params
      params[:video]
      params.require(:video).permit(:content, :description, :title, :room_id)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin_application'
  
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include TheRole::Controller
  
  protect_from_forgery

  helper_method :current_or_guest_user

  def current_or_guest_user
    if current_user
      if session[:guest_user_id]
        logging_in
        guest_user.destroy
        session[:guest_user_id] = nil
      end
      current_user
    else
      guest_user
    end
  end

  def guest_user
    # Cache the value the first time it's gotten.
    @cached_guest_user ||= User.find(session[:guest_user_id] ||= create_guest_user.id)

  rescue ActiveRecord::RecordNotFound # if session[:guest_user_id] invalid
     session[:guest_user_id] = nil
     guest_user
  end

  def access_denied
    flash[:error] = t('the_role.access_denied')
    redirect_to(:back)
  end

  private 
  def last_page count, per
    page = count / per
    count % per == 0 ? page : (page + 1) 
  end

  def create_guest_user
    id = "#{Time.now.to_i}#{rand(99)}#{rand(99)}"[8..-1]
    u = User.create(name: id, email: "guest_#{id}@sosnu.li")
    u.save!(validate: false)
    session[:guest_user_id] = u.id
    u
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  def index
    @discussions = Discussion.page(params[:page]).per(12)
  end

  def show
    @discussion = Discussion.find(params[:id])
    @posts = @discussion.posts.page(params[:page]).per(5)
  end

  def edit
    @discussions = Discussion.find params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :role_required,  only: [:index]
  before_action :login_required, except: [:index, :show]
  before_action :role_required,  except: [:index, :show]

  before_action :set_page,       only: [:edit, :update, :destroy]
  before_action :owner_required, only: [:edit, :update, :destroy]

  def index
    @room = Room.find('evromaidan')
    # @discussions = @room.discussions.page(params[:disc_page]).per(9)
    @discussions = @room.discussions.page(params[:page]).per(12)
    # @videos = @room.videos.page(params[:vi_page]).per(9)

    respond_to do |format|
      format.html
      format.js # add this line for your js template
    end


  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_filter :authenticate_user!
  before_filter :find_discussion
  before_filter :setup_negative_captcha, only: [:new, :create]

  def create
    # binding.pry
    post = @discussion.posts.new post_params
    post.user = current_or_guest_user
    post.save 

    redirect_to discussion_path(@discussion, page: last_page(@discussion.posts.count, 5))
  end

  private 

  def find_discussion
    @discussion = Discussion.find params[:discussion_id]
  end

  def post_params
    params.require(:post).permit(:content, :discussion_id, :user_id)
  end

  private
  def setup_negative_captcha
    @captcha = NegativeCaptcha.new(
      # A secret key entered in environment.rb. 'rake secret' will give you a good one.
      secret: NEGATIVE_CAPTCHA_SECRET,
      spinner: request.remote_ip, 
      # Whatever fields are in your form
      fields: [:name, :email, :body],  
      params: params
    )
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
  end

  def vkontakte
  	user = User.find_for_vkontakte_oauth request.env["omniauth.auth"]
    if user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Vkontakte"
      sign_in_and_redirect user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def show
    @video = Video.find(params[:id])
  end
end

app/helpers/admin/videos_helper.rb
module Admin::VideosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


  def devise_mapping
    Devise.mappings[:user]
  end
 
  def resource_name
    devise_mapping.name
  end

  def resource_class
    devise_mapping.to
  end

  def user_name
    current_user.name.present? ? current_user.name : 'Пользователь'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/admin/discussions/_form.html.haml
= simple_form_for [:admin, @discussion] do |f|
  - if @discussion.errors.any?
    #error_explanation
      %h2= "#{pluralize(@discussion.errors.count, "error")} prohibited this discussion from being saved:"
      %ul
        - @discussion.errors.full_messages.each do |msg|
          %li= msg
  = f.input :title    
  = f.input :short, as: :text 
  = f.input :description, as: :text
  = f.input :room_id, as: :select, collection: Room.all
  .actions
    = f.button :submit

app/views/admin/discussions/edit.html.haml
%h1 Editing discussion

= render 'form'

= link_to 'Show', @admin_discussion
\|
= link_to 'Back', admin_discussions_path

app/views/admin/discussions/index.html.haml
%h1 Listing discussions

%table
  %tr
    %th
    %th
    %th

  - @discussions.each do |discussion|
    %tr
      %td= discussion.title
      %td= link_to 'Show', polymorphic_path([:admin, discussion])
      %td= link_to 'Edit', edit_admin_discussion_path(discussion)
      %td= link_to 'Destroy', polymorphic_path([:admin, discussion]), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Video', new_admin_discussion_path

app/views/admin/discussions/new.html.haml
%h1 New discussion

= render 'form'

= link_to 'Back', admin_discussions_path

app/views/admin/discussions/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_admin_discussion_path(@discussion)
\|
= link_to 'Back', admin_discussions_path

app/views/admin/index.html.haml
%p Админка
%p= link_to 'roles', admin_roles_path
%p= link_to 'videos', admin_videos_path
%p= link_to 'discussions', admin_discussions_path

app/views/admin/videos/_form.html.haml
= simple_form_for [:admin, @video] do |f|
  - if @video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      %ul
        - @video.errors.full_messages.each do |msg|
          %li= msg
  = f.input :title    
  = f.input :description, as: :text
  = f.input :content, as: :text
  = f.input :room_id, as: :select, collection: Room.all
  .actions
    = f.button :submit

app/views/admin/videos/edit.html.haml
%h1 Editing admin_video

= render 'form'

= link_to 'Show', @admin_video
\|
= link_to 'Back', admin_videos_path

app/views/admin/videos/index.html.haml
%h1 Listing videos

%table
  %tr
    %th
    %th
    %th

  - @videos.each do |video|
    %tr
      %td= video.title
      %td= link_to 'Show', polymorphic_path([:admin, video])
      %td= link_to 'Edit', edit_admin_video_path(video)
      %td= link_to 'Destroy', polymorphic_path([:admin, video]), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Video', new_admin_video_path

app/views/admin/videos/new.html.haml
%h1 New admin_video

= render 'form'

= link_to 'Back', admin_videos_path

app/views/admin/videos/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_admin_video_path(@video)
\|
= link_to 'Back', admin_videos_path

app/views/discussions/_discussions.html.haml
- arr = [3,6,3]
- discussions.each_slice(3) do |disc_gr|
  - arr.shuffle!
  .row
    - disc_gr.each_with_index do |disc, i|
      .columns{class: "large-#{arr[i]}"}
        .panel.main-panel
          %h5= truncate(disc.title, length: 17)
          %p= truncate(disc.short, length: 17)

app/views/discussions/_posts_list.html.haml
- @posts.each do |post|
  .so-post-show
    .so-post-info
      %p
        = "##{post.id}"
      %p
        = post.user.name
    .so-post-content
      = post.content
= paginate @posts, remote: true

app/views/discussions/_show.html.haml
.so-discussion-popup
  .title
    = discussion.title
  .description
    = discussion.description

  .content
    .so-discussion-posts-list
      - if posts.present?
        = render 'posts_list', posts: posts
    .so-new-post
      - if user_signed_in?
        = simple_form_for [discussion, Post.new], remote: true do |f|
          = f.input :content, input_html: { maxlength: 20 }, label: false
          = f.button :submit, class: 'send-post'

app/views/discussions/index.js.haml
$('#so-discussions-list').append("#{ j(render 'discussions', discussions: @discussions) }");

$('a#load-more-discussions').attr('href', '#{discussions_path page: @discussions.next_page}');
 
- unless @discussions.next_page
  $('a#load-more-discussions').remove();

app/views/discussions/short/_discussion.html.haml
.title
  = discussion.title
.description
  = discussion.description

.content
  .so-discussion-posts-list
    = render 'discussions/posts_list', posts: @posts
  .so-new-post
    = simple_form_for [discussion, Post.new], remote: true do |f|
      = f.input :content, input_html: { maxlength: 20 }, label: false
      = f.button :submit, class: 'send-post'

app/views/discussions/short/_discussions_list.html.haml
- discussions.each do |discussion|
  .so-discussion{class: "so-disc-id-#{discussion.id}"}
    .so-discussion-id
      = "#d#{discussion.id}"
    .so-discussion-title
      = discussion.title
    .so-discussion-short
      = discussion.short
    = link_to 'Перейти', discussion_path(discussion), remote: true, class: 'so-link-to-discussion hide'




-# = paginate discussions, param_name: :disc_page, remote: true

app/views/discussions/show.html.haml
disc

app/views/discussions/show.js.erb
<% if params[:page].present? %>
$('.so-discussion-posts-list').html("<%= j(render 'posts_list', discussion: @discussion, posts: @posts) %>");
$('#new_post').find('textarea').val(' ');
<% else %>
$('#edit').html("<%= j(render 'show', discussion: @discussion, posts: @posts) %>");
$.fancybox.open($('#edit'), { fitToView: false, scrollOutside : true,
                            padding: 25,
                            closeBtn: false,
                            helpers:  { overlay : {locked : true} }   
                          });
<% end %>

app/views/home/index.html.haml
/ Main Grid Section
.row
  .large-12.column
    #so-logo.panel
      #so-main-title
        .small-12.medium-6.large-6.columns
          %h1 #Евромайдан
          %h5 Самые свежие ахуитительные новости
    -# %img{src: "http://placehold.it/1600x600&text=Header"}/

#so-discussions-list
  = render 'discussions/discussions', discussions: @discussions
= link_to 'Загрузить ещё', discussions_path(:page => @discussions.next_page), id: 'load-more-discussions', class: 'button', remote: true if @discussions.next_page
-# .row
-#   .large-6.columns
-#     .panel
-#       %h5 Panel Title
-#       %p This is a six columns grid panel with an arbitrary height. Bacon ipsum dolor sit amet salami ham hock biltong ball tip drumstick sirloin pancetta meatball short loin.
-#   .large-2.columns
-#     .panel
-#       %p
-#         %img{src: "http://placehold.it/200x200"}/
-#   .large-4.columns
-#     .panel
-#       %h5 Panel Title
-#       %p This is a four columns grid panel with an arbitrary height. Bacon ipsum dolor sit amet salami.
-# .row
-#   .large-4.columns
-#     .panel
-#       %p
-#         %img{src: "http://placehold.it/400x300"}/
-#   .large-4.columns
-#     .panel
-#       %p
-#         %img{src: "http://placehold.it/400x300"}/
-#   .large-4.columns
-#     .panel
-#       %p
-#         %img{src: "http://placehold.it/400x300"}/
-# .row
-#   .large-6.columns
-#     .panel
-#       %h5 Panel Title
-#       %p This is a six columns grid panel with an arbitrary height. Bacon ipsum dolor sit amet salami ham hock biltong ball tip drumstick sirloin pancetta meatball short loin.
-#   .large-3.columns
-#     .panel
-#       %h5 Panel Title
-#       %p This is a three columns grid panel with an arbitrary height.
-#   .large-3.columns
-#     .panel
-#       %h5 Panel Title
-#       %p This is a three columns grid panel with an arbitrary height.
-# / End Grid Section
-#




-# .so-li-logo 
-# #so-content
-#   #so-logo
-#     .center
-#       %h1.big= link_to '#Евромайдан', '#' 
-#       sosnu.li
-#
-#   #so-discussions-list
-#     = render 'discussions/short/discussions_list', discussions: @discussions
-#
-# -# #sv-room-content
-# -#   #so-videos-list
-# -#     = render 'videos/short/videos_list', videos: @videos
-# -#   .clear
-# -#   .so-separation-line
-# -#     = link_to '/\\', '#', id: 'slide-center-up'
-# -#     = link_to '\\/', '#', id: 'slide-center-down'
-# -#   #so-discussions-list
-# -#     = render 'discussions/short/discussions_list', discussions: @discussions

app/views/home/index.js.erb
<% if params[:disc_page].present? %>
$('#so-discussions-list').html("<%= j(render 'discussions/short/discussions_list', discussions: @discussions) %>");
<% elsif params[:vi_page].present?%>
$('#so-videos-list').html("<%= j(render 'videos/short/videos_list', videos: @videos) %>");
<%end%>

app/views/layouts/_footer.html.haml
/ Footer
%footer.row
  .large-12.columns
    %hr/
    .row
      .large-6.columns
        %p  sosnu.li 2014

app/views/layouts/_header.html.haml
= render 'layouts/header_nav'

- unless user_signed_in?
  #so-login{style: "display:none;"}
    %ul.so-modal-tabs.clearfix
      %li.active= link_to 'Вход', '', 'data-js' => 'link-tab-login'
      %li= link_to 'Регистрация', '', 'data-js' => 'link-tab-register'
    .tab-content
      #tab-login.tab-pane.active.clearfix= render 'devise/sessions/new', data_view: :madal
      #tab-register.tab-pane= render 'devise/registrations/new', user: User.new
      #tab-forgot-password.tab-pane= render 'devise/passwords/new'

app/views/layouts/_header_nav.html.haml
.row
  .large-12.columns
    %ul.button-group.left
      %li
        %a.button.tiny{href: "#"} Sosnu.li

    .button-group.right
      - if user_signed_in?
        = link_to user_name, '#', class: 'button tiny dropdown', 'data-dropdown' => 'drop'
        %br
        %ul#drop.f-dropdown{"data-dropdown-content" => ""}
          %li
            = link_to 'Выйти', destroy_user_session_path, method: :delete
      - else
        = link_to 'Вход', '#so-login', class: 'button tiny so-login'

app/views/layouts/admin_application.html.haml
!!!
%html
  %head
    %title Admin - sosnu.li
    = stylesheet_link_tag    'application', media: "all"
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = yield
    = yield :role_sidebar
    = yield :role_main

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : 'Sosnu.li' %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div id="so-content">

        <%= render 'layouts/header'%>
        <%= yield %>
        <%= render 'layouts/footer'%>

        <div id="edit">
          <div id="popup" class="model hide fade" data-replace="true" tabindex="-1">
            <div class="content">
            </div>
          </div>
        </div> 
        <%= javascript_include_tag "application" %>
      </div>
    </div>
  </body>

</html>

app/views/videos/short/_videos_list.html.haml
- videos.each do |v|
  .so-video
    / .so-video-title
    /   = video.title
    / .so-video-description
    /   = video.description
    .so-video-content
      .so-video-list-block{ 'data-js' => 'video' }
        .youtube[v]
          = link_to '', video_path(v), class: 'video so-video-link', data: { title: truncate(v.title, length: 20), youtube: v.content }, remote: true
          .sv-firm-video-link-bg
.clear
= paginate videos, param_name: :vi_page, remote: true